// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfQlHjZtvZVN4E9MENku48muL1JZpiUI',
    appId: '1:950022141408:web:f9bd870c1d0868514de785',
    messagingSenderId: '950022141408',
    projectId: 'aircharge-6b02d',
    authDomain: 'aircharge-6b02d.firebaseapp.com',
    storageBucket: 'aircharge-6b02d.appspot.com',
    measurementId: 'G-PQM2JV2PCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Gn_q5nO4AVw5-vKVD97pIGbnFCzVvU0',
    appId: '1:950022141408:android:decdd985e020ddf64de785',
    messagingSenderId: '950022141408',
    projectId: 'aircharge-6b02d',
    storageBucket: 'aircharge-6b02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhowNobvDnXBYtcqz9YNH6aNulZ3uJcs',
    appId: '1:950022141408:ios:d141704d294d71ae4de785',
    messagingSenderId: '950022141408',
    projectId: 'aircharge-6b02d',
    storageBucket: 'aircharge-6b02d.appspot.com',
    iosBundleId: 'com.example.aircharge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhowNobvDnXBYtcqz9YNH6aNulZ3uJcs',
    appId: '1:950022141408:ios:5e76e5b147108bc44de785',
    messagingSenderId: '950022141408',
    projectId: 'aircharge-6b02d',
    storageBucket: 'aircharge-6b02d.appspot.com',
    iosBundleId: 'com.example.aircharge.RunnerTests',
  );
}
